## 前言

在开始之前，还是看看上篇文章 AJAX 代码。
```JavaScript
button.addEventListener("click", e => {
  let request = new XMLHttpRequest();
  request.open("GET", "/yyzcl");
  request.setHeader("yyzcl","OK");
  request.send("Yyzcl");
  request.onreadystatechange = () => {
    if (request.readyState === 4) {
      let string = request.responseText;
      let obj = window.JSON.parse(string);
    }
  };
});
```
在这里，将这些代码封装一下，并增加成功失败判断调取对应的函数，然后去调用它。
```JavaScript
window.jQuery.ajax = function({ url, method, body, successFn, failFn, headers }) {
    let request = new XMLHttpRequest();
    request.open(method, url);
    for (let key in headers) {
      let value = headers[key];
      request.setRequestHeader(key, value);
    }
    request.onreadystatechange = () => {
      if (request.readyState === 4) {
        if (request.status >= 200 && request.status < 300) {
          successFn.call(undefined, request.responseText);
        } else if (request.status >= 400) {
          failFn.call(undefined, request);
        }
      }
    };
    request.send(body);
};

button.addEventListener("click", e => {
  window.jQuery
    .ajax({
      url: "/yyzcl",
      method: "get",
      body: "Yyzcl",
      successFn: (responseText) => {
        amount.innerText = amount.innerText - 1;
        return responseText;
      },
      failFn: (request) => {
        console.log("通讯失败");
        return request;
      }
    })
});
```
在使用`window.jQuery.ajax`的封装时，必须同时将成功失败函数一起传递进去，而且必须知道成功失败函数的名字（不同库的`ajax`的成功失败函数名有可能不一样），这就显得十分的麻烦，而`Promise`则很好地解决了这个问题。

## Promise

Promise 对象是 JavaScript 的异步操作解决方案，为异步操作提供统一接口。它起到代理作用（proxy），充当异步操作与回调函数之间的中介，使得异步操作具备同步操作的接口。Promise 可以让异步操作写起来，就像在写同步操作的流程，而不必一层层地嵌套回调函数。

## Promise 对象的状态

Promise 对象通过自身的状态，来控制异步操作。Promise 实例具有三种状态。

- 异步操作未完成（pending）
- 异步操作成功（fulfilled）
- 异步操作失败（rejected）

上面三种状态里面，`fulfilled`和`rejected`合在一起称为`resolved`（已定型）。

这三种的状态的变化途径只有两种。

- 从“未完成”到“成功”
- 从“未完成”到“失败”

一旦状态发生变化，就凝固了，不会再有新的状态变化。这也是 Promise 这个名字的由来，它的英语意思是“承诺”，一旦承诺成效，就不得再改变了。这也意味着，Promise 实例的状态变化只可能发生一次。

因此，Promise 的最终结果只有两种。

- 异步操作成功，Promise 实例传回一个值（value），状态变为`fulfilled`。
- 异步操作失败，Promise 实例抛出一个错误（error），状态变为`rejected`。

## Promise 构造函数

Promise 是一个对象，也是一个构造函数，下面看一个 Promise 例子。
```JavaScript
var promise = new Promise(function (resolve, reject) {
  // ...

  if (/* 异步操作成功 */){
    resolve(value);
  } else { /* 异步操作失败 */
    reject(error);
  }
});
```
`Promise`作为构造函数接受一个函数作为参数，这个函数接受两个函数（`resolve`和`reject`）作为参数。

在`Promise`异步操作成功时调用`resolve`函数，当异步操作失败时调用`reject`函数。

而`reslove`和`reject`函数可以用`then`传递进去。

## then

`then`方法可以接受两个回调函数，第一个是异步操作成功时（变为`fulfilled`状态）时的回调函数，第二个是异步操作失败（变为`rejected`）时的回调函数（该参数可以省略）。一旦状态改变，就调用相应的回调函数。

```JavaScript
var promise = new Promise(function (resolve, reject) {
  // ...

  if (/* 异步操作成功 */){
    resolve(value);
  } else { /* 异步操作失败 */
    reject(error);
  }
});

promise.then(
  (value) => {},
  (error) => {}
).then(
  (value) => {},
  (error) => {}
)
```
`then`支持链式操作，`then`之后可以继续接`then`，不过后面的`then`里面函数的参数时前面的`then`的返回结果。

采用链式的`then`，可以指定一组按照次序调用的回调函数。这时，前一个回调函数，有可能返回的还是一个`Promise`对象（即有异步操作），这时后一个回调函数，就会等待该`Promise`对象的状态发生变化，才会被调用。

## catch

`catch`方法是`then(null, rejection)`的别名，用于指定发生错误时的回调函数。

```JavaScript
promise.then(
  null,
  (error) => {
    console.log(error)
  })

// 等同于
promise.catch(
  (error) => {
    console.log(error)
  }
)
```

Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个`catch`语句捕获。

```JavaScript
new Promise(function (resolve, reject) {
  //some code
}).then(function(post) {
  return new Promise(function (resolve, reject) {});
}).then(function(comments) {
  // some code
}).catch(function(error) {
  // 处理前面三个Promise产生的错误
});
```

上面代码中，一共有三个 Promise 对象：一个由`new Promise`产生，两个由`then`产生。它们之中任何一个抛出的错误，都会被最后一个`catch`捕获。

一般来说，不要在`then`方法里面定义 Reject 状态的回调函数（即`then`的第二个参数），总是使用`catch`方法。
```JavaScript
// bad
promise
  .then(function(data) {
    // success
  }, function(err) {
    // error
  });

// good
promise
  .then(function(data) { 
    // success
  })
  .catch(function(err) {
    // error
  });
```
上面代码中，第二种写法要好于第一种写法，理由是第二种写法可以捕获前面`then`方法执行中的错误，也更接近同步的写法（`try/catch`）。因此，建议总是使用`catch`方法，而不使用`then`方法的第二个参数。

跟传统的`try/catch`代码块不同的是，如果没有使用`catch`方法指定错误处理的回调函数，Promise 对象抛出的错误不会传递到外层代码，即不会有任何反应。也就是 Promise 的错误不会影响外部代码的运行，通俗的说法就是“Promise 会吃掉错误”。

`catch`方法返回的还是一个 Promise 对象，因此后面还可以接着调用`then`方法。如果没有报错，则会跳过`catch`方法，直接执行后面的`then`方法。此时，要是后面的`then`方法里面报错，就与前面的`catch`无关了。

```JavaScript
Promise.resolve()
.catch(function(error) {
  console.log('oh no', error);
})
.then(function() {
  console.log('carry on');
});
// carry on
```

`catch`里面也可以抛出错误，这个错误可以被之后的`catch`捕获。

## finally

`finally`方法用于指定不管 Promise 对象最后状态如何，都会执行的操作。该方法是 ES2018 引入标准的。

```JavaScript
promise
.then(result => {···})
.catch(error => {···})
.finally(() => {···});
```

上面代码中，不管`promise`最后的状态，在执行完`then`或`catch`指定的回调函数以后，都会执行`finally`方法指定的回调函数。

`finally`方法的回调函数不接受任何参数，这意味着没有办法知道，前面的 Promise 状态到底是`fulfilled`还是`rejected`。这表明，`finally`方法里面的操作，应该是与状态无关的，不依赖于 Promise 的执行结果。

`finally`本质上是`then`方法的特例，即`then`成功或失败的执行代码是一样的。

## Promise 运行顺序
`promise`在新建之后会立即执行，而调用`promise`之后`then`方法的回调函数，将在当前脚本所有的同步任务全部完成之后才会执行.

```JavaScript
let promise = new Promise(function(resolve, reject) {
  console.log('Promise');
  resolve();
});

promise.then(function() {
  console.log('resolved.');
});

console.log('Hi!');

// Promise
// Hi!
// resolved
```

上面代码中，`promise`新建后立即执行，所以首先输出的是`Promise`。然后，`then`方法指定的回调函数，将在当前脚本所有同步任务执行完才会执行，所以`resolved`最后输出。

注意，调用`resolve`或`reject`并不会终结 Promise 的参数函数的执行。

```JavaScript
new Promise((resolve, reject) => {
  resolve(1);
  console.log(2);
}).then(r => {
  console.log(r);
});
// 2
// 1
```

上面代码中，调用`resolve(1)`以后，后面的`console.log(2)`还是会执行，并且会首先打印出来。这是因为立即 resolved 的 Promise 是在本轮事件循环的末尾执行，总是晚于本轮循环的同步任务。

一般来说，调用`resolve`或`reject`以后，Promise 的使命就完成了，后继操作应该放到`then`方法里面，而不应该直接写在`resolve`或`reject`的后面。所以，最好在它们前面加上`return`语句，这样就不会有意外。

```JavaScript
new Promise((resolve, reject) => {
  return resolve(1);
  // 后面的语句不会执行
  console.log(2);
})
```

## 重新封装 ajax

有了`Promise`之后，上面的`ajax`封装就可以这么写：
```JavaScript
window.jQuery.ajax = function({ url, method, body, headers }) {
    return new Promise (function (resolve, reject){
        let request = new XMLHttpRequest();
        request.open(method, url);
        for (let key in headers) {
          let value = headers[key];
          request.setRequestHeader(key, value);
        }
        request.onreadystatechange = () => {
          if (request.readyState === 4) {
            if (request.status >= 200 && request.status < 300) {
              successFn.call(undefined, request.responseText);
            } else if (request.status >= 400) {
              failFn.call(undefined, request);
            }
          }
        };
        request.send(body);
    })
};

button2.addEventListener("click", e => {
  window.jQuery
    .ajax({
      url: "/yyzcl",
      method: "get",
      body: "Yyzcl",
    })
    .then(
      (responseText) => {
        amount.innerText = amount.innerText - 0 + 1;
        return responseText;
      },
      (request) => {
        console.log("通讯失败");
        return request;
      });
});
```
从上面的代码可以知道，当我们调用封装好的`ajax`接口，并不需要知道成功失败函数的名字，直接利用`then`传递进去即可，使 AJAX 的使用变得更加简单。

## 小结

Promise 的优点在于，让回调函数变成了规范的链式写法，程序流程可以看得很清楚。它有一整套接口，可以实现许多强大的功能，比如同时执行多个异步操作，等到它们的状态都改变以后，再执行一个回调函数；再比如，为多个回调函数中抛出的错误，统一指定处理方法等等。

而且，Promise 还有一个传统写法没有的好处：它的状态一旦改变，无论何时查询，都能得到这个状态。这意味着，无论何时为 Promise 实例添加回调函数，该函数都能正确执行。所以，你不用担心是否错过了某个事件或信号。如果是传统写法，通过监听事件来执行回调函数，一旦错过了事件，再添加回调函数是不会执行的。

Promise 的缺点是，编写的难度比传统写法高，而且阅读代码也不是一眼可以看懂。你只会看到一堆`then`，必须自己在`then`的回调函数里面理清逻辑。



